fix: dns-json response.Answer may be undefined
This fixes an error seen in CI when response.Answer.filter() was called
and we got an error:

  TypeError: Cannot read properties of undefined (reading 'filter')
    at findDNSLinkAnswer (file:///home/runner/work/helia-ipns/helia-ipns/packages/ipns/src/utils/dns.ts:45:34)
    at ipfsPath (file:///home/runner/work/helia-ipns/helia-ipns/packages/ipns/src/utils/dns.ts:29:18)
    at httpQueue.add.signal (file:///home/runner/work/helia-ipns/helia-ipns/packages/ipns/src/dns-resolvers/dns-json-over-https.ts:71:22)